Models/Afiliado.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Entities.Models
{
    public class Afiliado : IdentityBase
    {
        [Required(ErrorMessage = "Requerido")]
        [MaxLength(25)]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Requerido")]
        [MaxLength(25)]
        public string Apellido { get; set; }

        [Required(ErrorMessage = "Requerido")]
        [MaxLength(35)]
        [EmailAddress(ErrorMessage = "Email incorrecto")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Requerido")]
        [DisplayName("Teléfono")]
        public long Telefono { get; set; }

        [Required(ErrorMessage = "Requerido")]
        public long Cuit { get; set; }

        [NotMapped]
        public string FullName
        {
            get
            {
                return Nombre + " " + Apellido;
            }
        }
    }
}

Models/IdentityBase.cs
using System.ComponentModel.DataAnnotations;

namespace Entities.Models
{
    public class IdentityBase
    {
        [Key]
        public int Id { get; set; }
    }
}

Controllers/AfiliadoController.cs
using Domain.Data;
using Entities.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace apellido_nombre_lppa_parcial1.Controllers
{
    public class AfiliadoController : Controller
    {
        BaseDataService<Afiliado> db;
        public AfiliadoController()
        {
            db = new BaseDataService<Afiliado>();
        }

        [HttpGet]
        public ActionResult Index()
        {
            var list = db.Get();
            return View(list);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Afiliado model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Create(model);
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {

                    Console.WriteLine("Gestor de la Exception...");
                }

            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = db.GetById(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Afiliado model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(model);
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {

                    Console.WriteLine("Gestor de la Exception...");
                }

            }
            return View(model);
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            var model = db.GetById(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(Afiliado model)
        {
            try
            {
                db.Delete(model.Id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Gestor de la Exception...");
            }
            return View(model);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace tesdtParcial2.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Views/Afiliado/Create.cshtml
@model Entities.Models.Afiliado

@{ ViewBag.Title = "Create"; }

<h2>Create</h2>

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Afiliado</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Cuit, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Cuit, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Cuit, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Guardar" class="btn btn-default" />
                        </div>
                    </div>
                </div>
                                }

Views/Afiliado/Delete.cshtml
@model Entities.Models.Afiliado

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar</h2>

<h3>¿Quiere eliminar este Item?</h3>
<div>
    <h4>Afiliado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cuit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cuit)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Lista de afiliados", "Index")
        </div>
    }
</div>

Views/Afiliado/Edit.cshtml
@model Entities.Models.Afiliado

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Afiliado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cuit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cuit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cuit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Lista de afiliados", "Index")
</div>

Views/Afiliado/Index.cshtml
@model IEnumerable<Entities.Models.Afiliado>

@{ ViewBag.Title = "Index"; }

<h2>Afiliados de la Obra Social</h2>

<table class="table">
    <tr>
        <th>
            @Html.Raw("Nombre y Apellido")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.Raw("CUIT")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.FullName)
    </td>
    <td class="email">
        @Html.DisplayFor(modelItem => item.Email)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Cuit)
    </td>
    <td>
        @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
        @Html.ActionLink("Eliminar", "Delete", new { id = item.Id })
    </td>
</tr>}

</table>

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<h2>About</h2>
<h3>apellido-nombre-lppa-parcial1</h3>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Pagina home</h2>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/site.css" rel="stylesheet" />
</head>
<body>
    <div id="contenedor">
        <div id="cabecera">
            <div id="logo">
                <h1></h1>
            </div>
            <div id="buscador">
                <form action="#" method="post">
                    Buscar &nbsp;
                    <input name="busqueda" type="text" />
                </form>
            </div>
            <div class="clear">
            </div>
        </div>
        <div id="menu">
            <ul id="menu_principal">
                <li> <a href="/">Home</a> </li>
                <li> <a href="/Home/About">About</a> </li>
                <li>
                    <a href="@Url.Action("Index", "Afiliado")">Afiliados</a>
                </li>
            </ul>
        </div>
        <div id="contenido">
            <div id="principal">
                @RenderBody()
            </div>
            <div id="secundario">
                <h2 id="nuevoAfiliado">@Html.ActionLink("Nuevo Afiliado", "Create")</h2>
            </div>
        </div>
        <div id="pie">
            <p> Datos de la WebSite - 2021</p>
        </div>

    </div>
</body>
</html>